/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description UI-facing identity read: exactly the context fields the shell needs.
         *
         *     `unit_breadcrumb` resolves the caller's unit path to readable unit names
         *     (oldest ancestor first) so the top bar can show "EIB Group > EIB Stratoc >
         *     Stratoc Site Team 4"; `permissions` is what the nav may offer — the server still
         *     enforces every action itself (SPEC 7.1).
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Records */
        get: operations["list_records_api_v1_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/records/{source_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Record
         * @description One record, through the adapter (policy row filter + RLS). 404 when not visible.
         */
        get: operations["get_record_api_v1_records__source_ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{source_ref}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_documents__source_ref__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}/chunks/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Chunk
         * @description Cited-passage viewer: open the exact page/section a citation points at.
         *
         *     Same authorization order and the same policy row filter + RLS as every
         *     other classified read. Anything not visible — including a caller whose
         *     action was denied, or a malformed id — answers 404 rather than 403, so a
         *     probe can never confirm that a restricted passage exists. `document_id`
         *     accepts the user-facing source_ref a citation carries, or the document's
         *     internal uuid.
         */
        get: operations["get_document_chunk_api_v1_documents__document_id__chunks__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit
         * @description Newest-first audit trail for the audit viewer (SPEC 14).
         *
         *     Every item carries `event_id`, so an answer's audit_event_id deep-links
         *     here with `?event_id=`.
         */
        get: operations["list_audit_api_v1_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit Verify
         * @description Chain verification plus both tamper-evidence layers (SPEC 14.2).
         */
        get: operations["audit_verify_api_v1_audit_verify_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Query Assistant */
        post: operations["query_assistant_api_v1_assistant_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description The caller's own conversations, newest first (SPEC §10.1).
         */
        get: operations["list_conversations_api_v1_assistant_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assistant/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description One of the caller's conversations with its turns and resolved citations.
         *
         *     A conversation owned by anyone else — or one the caller's action is not
         *     allowed to read — answers 404, exactly like the POST that appends to it,
         *     so an id can never be probed for existence.
         */
        get: operations["get_conversation_api_v1_assistant_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/home/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home Summary */
        get: operations["home_summary_api_v1_home_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/divisions/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Division View */
        get: operations["division_view_api_v1_divisions__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/divisions/{key}/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serial Trace
         * @description One serial number's run, QC state and delivery. Unseen and nonexistent read the same.
         */
        get: operations["serial_trace_api_v1_divisions__key__trace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Correlation */
        post: operations["run_correlation_api_v1_correlation_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Findings */
        get: operations["findings_api_v1_correlation_findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/correlation/findings/{finding_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Finding */
        get: operations["finding_api_v1_correlation_findings__finding_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connected/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connected Replay
         * @description STUB live feed: detections the caller may see, replayed in time order.
         *
         *     The synthetic detections are the "stream"; the client drives a replay clock and polls
         *     with `after` (the last observed_at it has) and `upto` (the clock). Stateless: the
         *     server holds no cursor. Stream and policy row filter + RLS come from the adapter, so
         *     an event the caller may not see is never read. Every poll is audited (a decide event
         *     and a query event with the ids delivered, possibly none).
         */
        get: operations["connected_replay_api_v1_connected_replay_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/connected/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connected Map
         * @description Sensors, recent detections and mission tracks the caller may see (never more).
         */
        get: operations["connected_map_api_v1_connected_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertPart */
        AlertPart: {
            /**
             * What
             * @description what is counted, e.g. 'deliveries overdue'
             */
            what: string;
            /** Count */
            count: number;
        };
        /** AssistantQueryRequest */
        AssistantQueryRequest: {
            /** Question */
            question: string;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** AssistantQueryResponse */
        AssistantQueryResponse: {
            /** Answer */
            answer: string;
            /** Citations */
            citations: components["schemas"]["CitationOut"][];
            /**
             * Found
             * @description false when nothing was found in approved sources, or a refusal
             */
            found: boolean;
            /**
             * Degraded
             * @description true when retrieval ran keyword-only (FTS only)
             */
            degraded: boolean;
            /**
             * Refused
             * @description true for permission-manipulation attempts, blocked answers and safe tool refusals
             */
            refused: boolean;
            /** @description deterministic tool output of the data pathway, else null */
            result_table?: components["schemas"]["ResultTable"] | null;
            /** @description set for a drafted report: draft flag and derived label */
            report?: components["schemas"]["ReportInfo"] | null;
            /** Conversation Id */
            conversation_id: string;
            /** Audit Event Id */
            audit_event_id: string;
        };
        /** CitationOut */
        CitationOut: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Title */
            document_title: string;
            /** Document Ref */
            document_ref: string;
            /** Page */
            page: number | null;
            /** Section */
            section: string | null;
            /** Classification Code */
            classification_code: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Classification Code */
            classification_code: string;
            /** Compartments */
            compartments: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Turns */
            turns: components["schemas"]["TurnOut"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Classification Code */
            classification_code: string;
            /** Compartments */
            compartments: string[];
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** DashboardItem */
        DashboardItem: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /**
             * Value
             * @description headline number, if the item has one
             */
            value: number | null;
            /**
             * Unit
             * @description what value counts, e.g. '%' or 'items'
             */
            unit: string | null;
            /** Detail */
            detail: string;
            /**
             * Severity
             * @description low | medium | high, where relevant
             */
            severity: string | null;
            /**
             * Trend
             * @description oldest to newest, for a flat sparkline
             */
            trend: number[];
            /** Classification */
            classification: string;
            /** Compartments */
            compartments: string[];
            /** Unit Path */
            unit_path: string;
            /**
             * Unit Name
             * @description readable name of the owning unit
             */
            unit_name: string;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Generated At */
            generated_at: string;
            tiles: components["schemas"]["DashboardTiles"];
        };
        /** DashboardTile */
        DashboardTile: {
            /**
             * Stub
             * @description true while the tile's data is placeholder data
             */
            stub: boolean;
            /** Source */
            source: string;
            /** Title */
            title: string;
            /** Items */
            items: components["schemas"]["DashboardItem"][];
        };
        /** DashboardTiles */
        DashboardTiles: {
            readiness: components["schemas"]["DashboardTile"];
            maintenance_backlog: components["schemas"]["DashboardTile"];
            expiring_certifications: components["schemas"]["DashboardTile"];
            overdue_deliveries: components["schemas"]["DashboardTile"];
            recent_findings: components["schemas"]["DashboardTile"];
        };
        /** DivisionView */
        DivisionView: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Tagline */
            tagline: string;
            /** Generated At */
            generated_at: string;
            /**
             * Sections
             * @description empty until this division's dashboard exists
             */
            sections: components["schemas"]["Section"][];
        };
        /** FindingOut */
        FindingOut: {
            /**
             * Id
             * @description stable finding id, e.g. FND-RISING-FAULTS-SITE-4
             */
            id: string;
            /** Analysis */
            analysis: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Severity */
            severity: string;
            /** Classification Code */
            classification_code: string;
            /** Compartments */
            compartments: string[];
            /** Unit Path */
            unit_path: string;
            /** Unit Name */
            unit_name: string;
            /**
             * Evidence Ids
             * @description record references (open via /records/{id})
             */
            evidence_ids: string[];
            /**
             * Details
             * @description the analysis parameters that produced it
             */
            details: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HomeAlert */
        HomeAlert: {
            /**
             * Count
             * @description everything in this division that needs attention
             */
            count: number;
            /** Parts */
            parts: components["schemas"]["AlertPart"][];
            /** Classification */
            classification: string;
            /** Compartments */
            compartments: string[];
        };
        /** HomeDivision */
        HomeDivision: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Tagline */
            tagline: string;
            /** @description null when nothing needs attention */
            alert: components["schemas"]["HomeAlert"] | null;
        };
        /** HomeSummary */
        HomeSummary: {
            /** Generated At */
            generated_at: string;
            /** Divisions */
            divisions: components["schemas"]["HomeDivision"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** RecordDetail */
        RecordDetail: {
            /** Source Ref */
            source_ref: string;
            /** Entity Type */
            entity_type: string;
            /** Source System */
            source_system: string;
            /** Classification Code */
            classification_code: string;
            /** Compartments */
            compartments: string[];
            /** Unit Path */
            unit_path: string;
            /** Retrieved At */
            retrieved_at: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /** ReportInfo */
        ReportInfo: {
            /**
             * Draft
             * @default true
             */
            draft: boolean;
            /** Classification Code */
            classification_code: string;
            /** Compartments */
            compartments: string[];
            /** Record Ids */
            record_ids: string[];
            /** Document Refs */
            document_refs: string[];
        };
        /** ResultTable */
        ResultTable: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** RunResult */
        RunResult: {
            /** Analysis */
            analysis: string;
            /** Findings */
            findings: components["schemas"]["FindingOut"][];
        };
        /** Section */
        Section: {
            /** Key */
            key: string;
            /** Title */
            title: string;
            /**
             * Tool
             * @description the typed tool that produced the rows
             */
            tool: string;
            /** Empty Text */
            empty_text: string;
            /** Flagged */
            flagged: number;
            /**
             * Classification
             * @description null when the section has no rows
             */
            classification: string | null;
            /** Compartments */
            compartments: string[];
            /** Rows */
            rows: components["schemas"]["SectionRow"][];
        };
        /** SectionRow */
        SectionRow: {
            /**
             * Ref
             * @description source record reference; links to /records/{ref}
             */
            ref: string;
            /** Label */
            label: string;
            /** Detail */
            detail: string;
            /**
             * Flagged
             * @description true when this row needs attention
             */
            flagged: boolean;
            /**
             * Meter
             * @description 0..1 gauge fill, e.g. hours flown of the interval
             */
            meter: number | null;
        };
        /** TurnOut */
        TurnOut: {
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
            /** Citations */
            citations?: components["schemas"]["CitationOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_documents_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | null;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_records_api_v1_records_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_record_api_v1_records__source_ref__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_documents__source_ref__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                source_ref: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_chunk_api_v1_documents__document_id__chunks__chunk_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                document_id: string;
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_api_v1_audit_get: {
        parameters: {
            query?: {
                limit?: number;
                /** @description return only this event */
                event_id?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    audit_verify_api_v1_audit_verify_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    query_assistant_api_v1_assistant_query_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantQueryRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantQueryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_v1_assistant_conversations_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_v1_assistant_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    home_summary_api_v1_home_summary_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HomeSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    division_view_api_v1_divisions__key__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DivisionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serial_trace_api_v1_divisions__key__trace_get: {
        parameters: {
            query: {
                serial: string;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Section"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_correlation_api_v1_correlation_run_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    findings_api_v1_correlation_findings_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_api_v1_correlation_findings__finding_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connected_replay_api_v1_connected_replay_get: {
        parameters: {
            query?: {
                after?: string | null;
                upto?: string | null;
                hours?: number;
                state?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    connected_map_api_v1_connected_map_get: {
        parameters: {
            query?: {
                hours?: number;
                mission_days?: number;
                state?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
