"""initial schema

Revision ID: d6fad2764629
Revises:
Create Date: 2026-10-06 11:49:32.168629
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "d6fad2764629"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Tables carrying classification/compartments/unit get row-level security.
CLASSIFIED_TABLES = ("documents", "chunks", "canonical_records")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("seq", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=True),
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_table(
        "classification_levels",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("rank"),
    )
    op.create_table(
        "compartments",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "units",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("path", sa.String(length=512), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["units.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
    )
    op.create_table(
        "source_systems",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("adapter_type", sa.String(length=64), nullable=False),
        sa.Column("default_classification", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["default_classification"],
            ["classification_levels.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("clearance_code", sa.String(length=32), nullable=True),
        sa.Column("keycloak_id", sa.String(length=128), nullable=True),
        sa.Column("data_scope", sa.String(length=16), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["clearance_code"],
            ["classification_levels.code"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("keycloak_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "canonical_records",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("entity_type", sa.String(length=64), nullable=False),
        sa.Column("source_system_id", sa.Uuid(), nullable=False),
        sa.Column("source_ref", sa.String(length=128), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("classification_code", sa.String(length=32), nullable=False),
        sa.Column("compartments", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_code"],
            ["classification_levels.code"],
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["source_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("source_system_id", sa.Uuid(), nullable=True),
        sa.Column("source_ref", sa.String(length=128), nullable=True),
        sa.Column("classification_code", sa.String(length=32), nullable=False),
        sa.Column("compartments", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_code"],
            ["classification_levels.code"],
        ),
        sa.ForeignKeyConstraint(
            ["source_system_id"],
            ["source_systems.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_compartments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("compartment_code", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["compartment_code"],
            ["compartments.code"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "compartment_code"),
    )
    op.create_table(
        "chunks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(1024), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("section", sa.String(length=128), nullable=True),
        sa.Column("classification_code", sa.String(length=32), nullable=False),
        sa.Column("compartments", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("unit_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["classification_code"],
            ["classification_levels.code"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Row-level security (SPEC 7.1 / 7.3). Literal rule, strictly downward:
    #   standard scope AND clearance >= row rank
    #   AND row.compartments <@ user.compartments
    #   AND starts_with(row.unit path, user unit path)   (starts_with, not LIKE)
    # Every current_setting is NULLIF-guarded: a cleared pooled connection
    # returns zero rows, never a cast error (AGENTS.md approved amendments).
    for _table in CLASSIFIED_TABLES:
        op.execute(f"ALTER TABLE {_table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"""
            CREATE POLICY {_table}_select ON {_table}
            FOR SELECT TO gateway_app
            USING (
                NULLIF(current_setting('app.data_scope', true), '') = 'standard'
                AND NULLIF(current_setting('app.clearance_rank', true), '')::int >= (
                    SELECT cl.rank FROM classification_levels cl
                    WHERE cl.code = {_table}.classification_code
                )
                AND {_table}.compartments::text[] <@ (
                    NULLIF(current_setting('app.compartments', true), '')::text[]
                )
                AND EXISTS (
                    SELECT 1 FROM units u
                    WHERE u.id = {_table}.unit_id
                      AND starts_with(
                          u.path, NULLIF(current_setting('app.unit_path', true), '')
                      )
                )
            )
            """
        )

    # Grants: the runtime role reads classified tables (RLS scopes the rows)
    # and appends to audit only — never UPDATE/DELETE (SPEC 14.2).
    op.execute(
        """
        GRANT SELECT ON
            classification_levels, compartments, units, users, user_compartments,
            source_systems, documents, chunks, canonical_records
        TO gateway_app
        """
    )
    op.execute("GRANT INSERT, SELECT ON audit_events TO gateway_app")
    op.execute("GRANT USAGE, SELECT ON SEQUENCE audit_events_seq_seq TO gateway_app")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chunks")
    op.drop_table("user_compartments")
    op.drop_table("documents")
    op.drop_table("canonical_records")
    op.drop_table("users")
    op.drop_table("source_systems")
    op.drop_table("units")
    op.drop_table("compartments")
    op.drop_table("classification_levels")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
