"""The original demo records (REC-001 onward)."""

from __future__ import annotations

# (ref, entity_type, source, classification, compartments, unit path, data)
RECORDS = [
    (
        "REC-001",
        "Equipment",
        "logistics-ref",
        "restricted",
        [],
        "/eib-group/stratoc/",
        {
            "equipment_id": "EQ-2201",
            "name": "Generator 15kW",
            "location": "EIB Stratoc depot",
            "service_due": "2026-11-01",
            "status": "in_service",
        },
    ),
    (
        "REC-002",
        "TrainingEvent",
        "training-ref",
        "restricted",
        [],
        "/eib-group/stratoc/site-4/",
        {
            "course": "Rifle Refresher",
            "start_date": "2026-08-11",
            "attendees": 24,
            "unit": "Stratoc Site Team 4",
        },
    ),
    (
        "REC-003",
        "WorkOrder",
        "logistics-ref",
        "confidential",
        [],
        "/eib-group/stratoc/site-4/",
        {
            "wo_ref": "WO-0455",
            "equipment": "Water Purifier WP-7",
            "state": "awaiting_parts",
            "raised": "2026-09-08",
        },
    ),
    (
        "REC-004",
        "Flight",
        "connected-tech-demo",
        "secret",
        ["UAS-OPS"],
        "/eib-group/briech/",
        {"tail": "UAS-14", "mission": "MSN-091", "duration_min": 47, "battery_pct_end": 61},
    ),
    (
        "REC-005",
        "StockItem",
        "logistics-ref",
        "restricted",
        [],
        "/eib-group/stratoc/",
        {"item": "Cold weather kit", "depot": "DEP-B2", "quantity": 320, "threshold": 150},
    ),
    (
        "REC-006",
        "Qualification",
        "personnel-ref",
        "restricted",
        [],
        "/eib-group/",
        {
            "person": "Sgt N. Yusuf",
            "qualification": "Armoured vehicle driver",
            "expires": "2027-02-28",
        },
    ),
    (
        "REC-007",
        "Case",
        "forensics-demo",
        "secret",
        ["FORENSICS"],
        "/eib-group/giga/",
        {
            "case_ref": "FR-2026-014",
            "title": "Handset and cloud extraction for Client Agency D",
            "opened": "2026-06-03",
            "state": "open",
            "lead_examiner": "A. Danjuma",
        },
    ),
    (
        "REC-008",
        "WorkOrder",
        "logistics-ref",
        "restricted",
        [],
        "/group-it/",
        {
            "wo_ref": "WO-0461",
            "equipment": "Badge printer GRP-IT",
            "state": "closed",
            "raised": "2026-09-21",
        },
    ),
    (
        "REC-009",
        "Equipment",
        "connected-tech-demo",
        "confidential",
        ["UAS-OPS"],
        "/eib-group/briech/",
        {
            "equipment_id": "UAS-14",
            "name": "Raven-II UAS",
            "flight_hours": 142.5,
            "next_service": "2026-12-15",
        },
    ),
    (
        "REC-010",
        "StockItem",
        "logistics-ref",
        "restricted",
        [],
        "/eib-group/stratoc/",
        {"item": "Generator oil 5L", "depot": "DEP-B2", "quantity": 45, "threshold": 60},
    ),
]
