"""Data-pathway demo rows: equipment, qualifications, faults, training."""

from __future__ import annotations

from app.seed.records.common import _SITE4, _STRATOC, _equipment, _fault, _qualification, _training

RECORDS = [
    _equipment(
        "REC-011",
        "logistics-ref",
        "restricted",
        [],
        _SITE4,
        -12,
        equipment_id="EQ-3101",
        name="Armoured Personnel Carrier APC-12",
        type="vehicle",
        status="in_service",
        location="Stratoc Site Team 4 motor pool",
    ),
    _equipment(
        "REC-012",
        "logistics-ref",
        "restricted",
        [],
        _SITE4,
        15,
        equipment_id="EQ-3102",
        name="Cargo Truck 5T",
        type="vehicle",
        status="in_service",
        location="Stratoc Site Team 4 motor pool",
    ),
    _equipment(
        "REC-013",
        "logistics-ref",
        "restricted",
        [],
        _STRATOC,
        10,
        equipment_id="EQ-3103",
        name="Field Radio Set FR-9",
        type="communications",
        status="in_service",
        location="EIB Stratoc signals store",
    ),
    _equipment(
        "REC-014",
        "logistics-ref",
        "confidential",
        [],
        _STRATOC,
        -3,
        equipment_id="EQ-3104",
        name="Generator 40kW",
        type="power",
        status="degraded",
        location="EIB Stratoc depot",
    ),
    _equipment(
        "REC-015",
        "logistics-ref",
        "confidential",
        [],
        _SITE4,
        20,
        equipment_id="EQ-3105",
        name="Water Purifier WP-7",
        type="utility",
        status="awaiting_parts",
        location="Stratoc Site Team 4 camp",
    ),
    _equipment(
        "REC-016",
        "logistics-ref",
        "restricted",
        [],
        "/eib-group/",
        15,
        equipment_id="EQ-3106",
        name="Recovery Vehicle RV-2",
        type="vehicle",
        status="in_service",
        location="EIB Group workshop",
    ),
    _equipment(
        "REC-017",
        "logistics-ref",
        "restricted",
        [],
        _SITE4,
        90,
        equipment_id="EQ-3107",
        name="Field Kitchen FK-3",
        type="catering",
        status="in_service",
        location="Stratoc Site Team 4 camp",
    ),
    _equipment(
        "REC-018",
        "connected-tech-demo",
        "secret",
        ["UAS-OPS"],
        "/eib-group/briech/",
        5,
        equipment_id="UAS-15",
        name="Raven-II UAS (tail 15)",
        type="uas",
        status="in_service",
        location="Briech UAS hangar",
    ),
    _qualification(
        "REC-019",
        "restricted",
        [],
        _SITE4,
        -30,
        name="Cpl B. Ibrahim",
        rank="Corporal",
        certification="First Aid",
    ),
    _qualification(
        "REC-020",
        "restricted",
        [],
        _SITE4,
        -10,
        name="Pte C. Nwosu",
        rank="Private",
        certification="Heavy Vehicle Driver",
    ),
    _qualification(
        "REC-021",
        "restricted",
        [],
        _STRATOC,
        -45,
        name="Sgt D. Okoye",
        rank="Sergeant",
        certification="Rifle Marksman",
    ),
    _qualification(
        "REC-022",
        "confidential",
        [],
        _STRATOC,
        -5,
        name="Capt E. Lawal",
        rank="Captain",
        certification="Signals Operator",
    ),
    _qualification(
        "REC-023",
        "secret",
        ["UAS-OPS"],
        "/eib-group/briech/",
        -20,
        name="Lt F. Garba",
        rank="Lieutenant",
        certification="UAS Pilot",
    ),
    _qualification(
        "REC-024",
        "restricted",
        [],
        "/eib-group/",
        -60,
        name="WO G. Abubakar",
        rank="Warrant Officer",
        certification="Armoured Vehicle Driver",
    ),
    _qualification(
        "REC-025",
        "restricted",
        [],
        _SITE4,
        200,
        name="Sgt H. Danladi",
        rank="Sergeant",
        certification="First Aid",
    ),
    # Stock rows for stock_below_threshold: one short and one healthy at Stratoc Site Team 4.
    (
        "REC-026",
        "StockItem",
        "logistics-ref",
        "restricted",
        [],
        _SITE4,
        {"item": "Water purifier filter", "depot": "DEP-B4", "quantity": 8, "threshold": 20},
    ),
    (
        "REC-027",
        "StockItem",
        "logistics-ref",
        "restricted",
        [],
        _SITE4,
        {"item": "Ration pack 24h", "depot": "DEP-B4", "quantity": 400, "threshold": 250},
    ),
    # Planted correlation pattern (Part D2): fault reports rise in Stratoc Site Team 4 while
    # its maintainers' certifications lapse (REC-041/042) and a spare-part line is
    # short (REC-026). EIB Stratoc's fault rate stays flat as the control. The newest
    # Site 4 report is Secret, so the derived finding inherits Secret (SPEC 7.2).
    # Windows are relative to the seed date: 42..22 days ago vs the last 21 days.
    _fault("REC-028", "restricted", _SITE4, -40, "APC-12", "Hydraulic leak, rear ramp"),
    _fault("REC-029", "restricted", _SITE4, -30, "Cargo Truck 5T", "Brake pressure warning"),
    _fault("REC-030", "restricted", _SITE4, -18, "APC-12", "Transmission slip under load"),
    _fault("REC-031", "restricted", _SITE4, -14, "Cargo Truck 5T", "Alternator failure"),
    _fault("REC-032", "restricted", _SITE4, -11, "Water Purifier WP-7", "Filter housing crack"),
    _fault("REC-033", "restricted", _SITE4, -8, "APC-12", "Coolant loss"),
    _fault("REC-034", "restricted", _SITE4, -5, "Cargo Truck 5T", "Steering play"),
    _fault("REC-035", "restricted", _SITE4, -3, "Water Purifier WP-7", "Pump seal failure"),
    _fault(
        "REC-036", "secret", _SITE4, -1, "Command vehicle secure radio", "Encryption module fault"
    ),
    _fault("REC-037", "restricted", _STRATOC, -38, "Generator 15kW", "Fuel pump fault"),
    _fault("REC-038", "restricted", _STRATOC, -28, "Generator 15kW", "Exhaust leak"),
    _fault("REC-039", "restricted", _STRATOC, -15, "Light Truck 2T", "Tyre wear"),
    _fault("REC-040", "restricted", _STRATOC, -6, "Light Truck 2T", "Clutch wear"),
    _qualification(
        "REC-041",
        "restricted",
        [],
        _SITE4,
        -18,
        name="Cpl J. Lawal",
        rank="Corporal",
        certification="Vehicle Maintainer",
    ),
    # training_activity data: REC-002 (fixed date) is the Site 4 baseline; these add a Stratoc
    # event, a Briech UAS event (Confidential, UAS-OPS) and one old Site 4 event outside a quarter.
    _training("REC-043", "restricted", [], _STRATOC, -35, "Vehicle Recovery", 18, "EIB Stratoc"),
    _training(
        "REC-044",
        "confidential",
        ["UAS-OPS"],
        "/eib-group/briech/",
        -20,
        "UAS Flight Qualification",
        6,
        "Briech UAS",
    ),
    _training(
        "REC-045", "restricted", [], _SITE4, -200, "Cold Weather Drills", 30, "Stratoc Site Team 4"
    ),
    _qualification(
        "REC-042",
        "restricted",
        [],
        _SITE4,
        -9,
        name="Pte S. Ogunleye",
        rank="Private",
        certification="Vehicle Maintainer",
    ),
]
